"""empty message

Revision ID: 886c6b7f9778
Revises: 2ce62d063d5a
Create Date: 2024-03-04 13:34:18.778686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886c6b7f9778'
down_revision = '2ce62d063d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etudiant', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
